import type { AnimationStyle, MotionTokens } from "../types"

export function getMotionTokens(animation: AnimationStyle): MotionTokens {
  const presets: Record<AnimationStyle, MotionTokens> = {
    none: {
      transition: "transition-none",
      transitionSlow: "transition-none",
      hoverLift: "",
      hoverScale: "",
      revealBase: "",
      revealHidden: "opacity-100",
      revealVisible: "",
      revealUp: "",
      revealLeft: "",
      revealRight: "",
      revealScale: "",
      revealFade: "",
      marquee: "",
    },
    subtle: {
      transition: "transition-all duration-300 ease-out",
      transitionSlow: "transition-all duration-300 ease-out",
      hoverLift: "hover:-translate-y-0.5",
      hoverScale: "hover:scale-[1.01]",
      revealBase: "transition-opacity duration-300 ease-out",
      revealHidden: "opacity-0",
      revealVisible: "opacity-100",
      revealUp: "translate-y-4",
      revealLeft: "-translate-x-4",
      revealRight: "translate-x-4",
      revealScale: "scale-[0.98]",
      revealFade: "",
      marquee: "animate-marquee motion-reduce:animate-none",
    },
    smooth: {
      transition: "transition-all duration-500 ease-out",
      transitionSlow: "transition-all duration-700 ease-out",
      hoverLift: "hover:-translate-y-1",
      hoverScale: "hover:scale-[1.02]",
      revealBase: "transition-all duration-700 ease-out",
      revealHidden: "opacity-0",
      revealVisible: "opacity-100 translate-x-0 translate-y-0 scale-100",
      revealUp: "translate-y-10",
      revealLeft: "-translate-x-10",
      revealRight: "translate-x-10",
      revealScale: "scale-95",
      revealFade: "",
      marquee: "animate-marquee motion-reduce:animate-none",
    },
    dynamic: {
      transition: "transition-all duration-500 ease-[cubic-bezier(0.16,1,0.3,1)]",
      transitionSlow: "transition-all duration-700 ease-[cubic-bezier(0.16,1,0.3,1)]",
      hoverLift: "hover:-translate-y-1.5",
      hoverScale: "hover:scale-[1.03]",
      revealBase: "transition-all duration-900 ease-[cubic-bezier(0.16,1,0.3,1)]",
      revealHidden: "opacity-0",
      revealVisible: "opacity-100 translate-x-0 translate-y-0 scale-100",
      revealUp: "translate-y-14",
      revealLeft: "-translate-x-14",
      revealRight: "translate-x-14",
      revealScale: "scale-90",
      revealFade: "",
      marquee: "animate-marquee motion-reduce:animate-none",
    },
    cinematic: {
      transition: "transition-all duration-1000 ease-[cubic-bezier(0.22,1,0.36,1)]",
      transitionSlow: "transition-all duration-1000 ease-[cubic-bezier(0.22,1,0.36,1)]",
      hoverLift: "hover:-translate-y-2",
      hoverScale: "hover:scale-[1.04]",
      revealBase: "transition-all duration-1000 ease-[cubic-bezier(0.22,1,0.36,1)]",
      revealHidden: "opacity-0 blur-[2px]",
      revealVisible: "opacity-100 translate-x-0 translate-y-0 scale-100 blur-0",
      revealUp: "translate-y-20",
      revealLeft: "-translate-x-20",
      revealRight: "translate-x-20",
      revealScale: "scale-[0.88]",
      revealFade: "blur-sm",
      marquee: "animate-marquee-slow motion-reduce:animate-none",
    },
  }
  return presets[animation]
}
