import type { LayoutStyle, LayoutTokens } from "../types"

export function getLayoutTokens(layout: LayoutStyle): LayoutTokens {
  const base = {
    container: "mx-auto max-w-6xl",
    section: "px-6 py-24",
    sectionAlt: "border-y border-primary/10 bg-panel/50 px-6 py-24",
    statsGrid: "grid grid-cols-3 gap-4",
  }

  const layouts: Record<LayoutStyle, LayoutTokens> = {
    grid: {
      ...base,
      heroGrid: "relative mx-auto grid max-w-6xl items-center gap-12 lg:grid-cols-[1fr_auto]",
      aboutGrid: "grid items-start gap-10 lg:grid-cols-[280px_1fr]",
      traitsGrid: "grid gap-3 sm:grid-cols-2",
      skillsGrid: "grid gap-6 md:grid-cols-3",
      projectsGrid: "grid gap-5 md:grid-cols-2",
      projectFeatured: "md:col-span-2 md:grid md:grid-cols-2",
      projectDefault: "",
      experienceList: "space-y-6",
      experienceItem: "grid gap-4 p-6 md:grid-cols-[140px_1fr]",
      contactGrid: "grid gap-10 lg:grid-cols-2",
    },
    bento: {
      ...base,
      container: "mx-auto max-w-7xl",
      heroGrid: "relative mx-auto grid max-w-7xl items-center gap-6 lg:grid-cols-12",
      aboutGrid: "grid gap-4 lg:grid-cols-12",
      traitsGrid: "grid grid-cols-2 gap-3 lg:col-span-8 lg:grid-cols-2",
      skillsGrid: "grid grid-cols-2 gap-4 md:grid-cols-3 lg:grid-cols-6",
      projectsGrid: "grid grid-cols-2 gap-4 md:grid-cols-4",
      projectFeatured: "col-span-2 row-span-2 md:col-span-2 md:row-span-2",
      projectDefault: "col-span-1",
      experienceList: "grid gap-4 md:grid-cols-2",
      experienceItem: "flex flex-col gap-3 p-5",
      contactGrid: "grid gap-6 lg:grid-cols-3",
    },
    timeline: {
      ...base,
      heroGrid: "relative mx-auto flex max-w-3xl flex-col items-center gap-10 text-center",
      aboutGrid: "flex flex-col gap-8",
      traitsGrid: "grid gap-4",
      skillsGrid: "flex flex-col gap-4 max-w-2xl mx-auto",
      projectsGrid: "flex flex-col gap-6 max-w-3xl mx-auto",
      projectFeatured: "",
      projectDefault: "",
      experienceList: "relative space-y-0 max-w-3xl mx-auto before:absolute before:inset-y-0 before:left-4 before:w-px before:bg-primary/30",
      experienceItem: "relative grid gap-4 py-6 pl-12 md:grid-cols-1",
      contactGrid: "flex flex-col gap-8 max-w-2xl mx-auto",
    },
    dashboard: {
      ...base,
      container: "mx-auto max-w-7xl",
      section: "px-4 py-16",
      sectionAlt: "border-y border-primary/10 bg-panel/60 px-4 py-16",
      heroGrid: "relative mx-auto grid max-w-7xl gap-4 lg:grid-cols-3",
      aboutGrid: "grid gap-4 lg:grid-cols-3",
      traitsGrid: "grid grid-cols-2 gap-3 lg:grid-cols-4",
      skillsGrid: "grid gap-4 sm:grid-cols-2 lg:grid-cols-3",
      projectsGrid: "grid gap-4 sm:grid-cols-2 lg:grid-cols-3",
      projectFeatured: "sm:col-span-2",
      projectDefault: "",
      experienceList: "grid gap-4",
      experienceItem: "grid gap-3 p-4 md:grid-cols-[120px_1fr]",
      contactGrid: "grid gap-6 lg:grid-cols-2",
      statsGrid: "grid grid-cols-3 gap-3",
    },
    magazine: {
      ...base,
      container: "mx-auto max-w-6xl",
      heroGrid: "relative mx-auto grid max-w-6xl gap-10 lg:grid-cols-12 lg:items-end",
      aboutGrid: "grid gap-8 lg:grid-cols-12",
      traitsGrid: "grid gap-4 sm:grid-cols-2 lg:col-span-7",
      skillsGrid: "grid gap-5 md:grid-cols-2 lg:grid-cols-3",
      projectsGrid: "grid gap-6 md:grid-cols-12",
      projectFeatured: "md:col-span-8 md:row-span-2",
      projectDefault: "md:col-span-4",
      experienceList: "space-y-8 max-w-4xl",
      experienceItem: "grid gap-6 border-l-2 border-accent/40 pl-8 md:grid-cols-1",
      contactGrid: "grid gap-12 lg:grid-cols-[1.2fr_1fr]",
    },
  }

  return layouts[layout]
}
