import type { ThemeName, ThemeClasses } from "./types"

type LightPatch = {
  colors?: Record<string, string>
  classes: Partial<ThemeClasses>
}

export const lightPatches: Record<ThemeName, LightPatch> = {
  cyberpunk: {
    colors: {
      bg: "#eef2f7",
      panel: "#ffffff",
      accent: "#0099aa",
      accent2: "#d61f5e",
      highlight: "#b8860b",
    },
    classes: {
      root: "min-h-screen bg-[#eef2f7] font-[Share_Tech_Mono] text-zinc-700",
      sectionAlt: "border-y border-cyan-600/15 bg-white/60 px-6 py-24",
      textPrimary: "text-zinc-900",
      textMuted: "text-zinc-600",
      textAccent: "text-[#007a8a]",
      textAccent2: "text-[#c4184f]",
      textHighlight: "text-[#9a7209]",
      panel:
        "relative border border-[#0099aa]/25 bg-white/90 shadow-[0_0_20px_rgba(0,153,170,0.08)] transition-all duration-500 hover:-translate-y-1.5 hover:border-[#d61f5e]/40 hover:shadow-[0_0_25px_rgba(214,31,94,0.12)]",
      btnPrimary:
        "inline-flex items-center gap-2 border border-[#007a8a] bg-[#0099aa]/15 px-6 py-3 font-[Orbitron] text-xs font-bold uppercase tracking-widest text-[#006b7a] transition-all duration-500 hover:bg-[#0099aa]/25",
      btnSecondary:
        "inline-flex items-center gap-2 border border-[#c4184f]/60 bg-transparent px-6 py-3 font-[Orbitron] text-xs font-bold uppercase tracking-widest text-[#b01545] transition-all duration-500 hover:bg-[#d61f5e]/10",
      tag: "inline-flex items-center gap-1.5 border border-[#0099aa]/30 bg-[#0099aa]/8 px-2 py-0.5 font-[Share_Tech_Mono] text-xs text-[#007a8a]",
      input:
        "w-full border border-[#0099aa]/25 bg-white px-4 py-3 font-[Share_Tech_Mono] text-sm text-zinc-800 placeholder:text-zinc-400 outline-none transition-all duration-500 focus:border-[#d61f5e]/50",
      badge:
        "inline-flex items-center gap-3 border border-emerald-600/35 bg-emerald-500/12 px-4 py-2 font-[Share_Tech_Mono] text-xs uppercase tracking-widest text-emerald-800",
      iconWrap:
        "flex h-9 w-9 items-center justify-center border border-[#0099aa]/30 bg-[#0099aa]/8 text-[#007a8a]",
      header: "fixed inset-x-0 top-0 z-50 border-b border-[#0099aa]/20 bg-white/90 backdrop-blur-sm",
      navLink:
        "relative px-3 py-2 font-[Share_Tech_Mono] text-xs uppercase tracking-widest text-zinc-600 transition-all duration-500 hover:text-[#007a8a]",
      navMobile: "block font-[Share_Tech_Mono] text-xs uppercase tracking-widest text-[#007a8a]",
      logo: "group flex items-center gap-2 font-[Orbitron] text-sm font-bold tracking-[0.2em] text-zinc-900",
      logoAccent: "text-[#007a8a]",
      logoDot: "text-[#c4184f]",
      sectionLabel: "font-[Share_Tech_Mono] text-xs uppercase tracking-[0.3em] text-[#c4184f]",
      sectionTitle: "font-[Orbitron] text-2xl font-bold uppercase tracking-wider text-zinc-900 sm:text-3xl",
      sectionTitlePrefix: "text-[#007a8a]",
      sectionDesc: "mt-5 max-w-2xl font-[Share_Tech_Mono] text-sm leading-relaxed text-zinc-600",
      heroBoot: "font-[Share_Tech_Mono] text-sm text-[#007a8a]",
      heroOperator: "block text-sm font-bold tracking-[0.4em] text-[#c4184f]",
      heroName: "mt-2 block text-[#006b7a]",
      heroSubtitle: "mt-6 max-w-lg font-[Share_Tech_Mono] text-sm leading-relaxed text-zinc-700",
      heroStackPill:
        "icon-hover flex items-center gap-2 border border-[#0099aa]/30 bg-[#0099aa]/8 px-3 py-1.5 text-[#007a8a]",
      statValue: "font-[Orbitron] text-2xl font-bold text-[#9a7209]",
      statLabel: "mt-1 font-[Share_Tech_Mono] text-[10px] uppercase tracking-wider text-zinc-600",
      statsBorder: "mt-14 grid grid-cols-3 gap-4 border-t border-[#0099aa]/20 pt-8",
      photoInner: "relative aspect-square overflow-hidden border border-[#0099aa]/30 bg-zinc-100",
      photoCaption:
        "absolute inset-x-0 bottom-0 bg-gradient-to-t from-white/95 to-transparent px-3 py-2 font-[Share_Tech_Mono] text-[9px] uppercase tracking-[0.25em] text-[#007a8a]",
      photoMeta:
        "mt-2 flex items-center justify-between px-1 font-[Share_Tech_Mono] text-[9px] uppercase tracking-widest text-zinc-500",
      projectThumb: "relative border-b border-[#0099aa]/15 bg-zinc-100",
      projectTitle: "font-[Orbitron] text-sm font-bold uppercase tracking-wider text-zinc-900",
      projectDesc: "mt-3 flex-1 font-[Share_Tech_Mono] text-xs leading-relaxed text-zinc-600",
      expRole: "font-[Orbitron] text-sm font-bold uppercase tracking-wider text-zinc-900",
      expCompany: "mt-1 font-[Share_Tech_Mono] text-xs text-[#007a8a]",
      skillCategoryTitle: "font-[Orbitron] text-sm font-bold uppercase tracking-widest text-zinc-900",
      skillRow: "flex items-center gap-3 rounded-sm px-2 py-1.5 font-[Share_Tech_Mono] text-sm text-zinc-600 transition-all duration-500 hover:bg-[#0099aa]/8 hover:text-[#007a8a]",
      marquee: "relative overflow-hidden border-y border-[#0099aa]/15 bg-white/80 py-5",
      marqueeFadeL: "pointer-events-none absolute inset-y-0 left-0 z-10 w-24 bg-gradient-to-r from-[#eef2f7] to-transparent",
      marqueeFadeR: "pointer-events-none absolute inset-y-0 right-0 z-10 w-24 bg-gradient-to-l from-[#eef2f7] to-transparent",
      marqueeItem: "flex items-center gap-3 text-zinc-500 transition-all duration-500 hover:scale-110 hover:text-[#007a8a]",
      footerText: "font-[Share_Tech_Mono] text-[10px] uppercase tracking-widest text-zinc-500",
      terminalInner: "border border-[#d61f5e]/20 bg-zinc-50 p-5",
      pickerPage: "min-h-screen bg-[#eef2f7] px-6 py-16",
      pickerCard: "group cursor-pointer border border-[#0099aa]/25 bg-white p-1 text-left shadow-sm",
      pickerPreview: "h-28 border border-[#0099aa]/15 bg-[#eef2f7] p-4",
      pickerCardLabel: "mt-4 font-[Orbitron] text-sm font-bold uppercase text-zinc-900",
      settingsBtn:
        "flex h-9 w-9 items-center justify-center border border-[#0099aa]/35 text-[#007a8a] transition-all duration-500 hover:border-[#c4184f]/50 hover:text-[#c4184f]",
      settingsOverlay: "fixed inset-0 z-[100] bg-white/80 backdrop-blur-sm",
      modeToggle: "inline-flex rounded-sm border border-[#0099aa]/30 bg-white p-0.5",
      modeToggleActive: "bg-[#0099aa]/15 text-[#006b7a]",
      showScanlines: false,
      showGlitch: false,
      showGridFloor: false,
    },
  },
  glassmorphism: {
    colors: {
      bg: "#f8fafc",
      panel: "rgba(255,255,255,0.85)",
      accent: "#0284c7",
      accent2: "#7c3aed",
      highlight: "#059669",
    },
    classes: {
      root: "min-h-screen bg-gradient-to-br from-sky-50 via-violet-50 to-emerald-50 font-[Inter] text-slate-700",
      textPrimary: "text-slate-900",
      textMuted: "text-slate-600",
      textAccent: "text-sky-700",
      textAccent2: "text-violet-700",
      textHighlight: "text-emerald-700",
      panel:
        "rounded-2xl border border-slate-200/80 bg-white/80 shadow-lg backdrop-blur-xl transition-all duration-700 hover:-translate-y-2 hover:shadow-xl",
      btnPrimary:
        "inline-flex items-center gap-2 rounded-full bg-gradient-to-r from-sky-600 to-violet-600 px-7 py-3.5 font-[Space_Grotesk] text-sm font-semibold text-white shadow-lg shadow-sky-500/20 transition-all duration-500 hover:-translate-y-0.5",
      btnSecondary:
        "inline-flex items-center gap-2 rounded-full border border-slate-300 bg-white/80 px-7 py-3.5 font-[Space_Grotesk] text-sm font-semibold text-slate-800 backdrop-blur-sm transition-all duration-500 hover:border-slate-400 hover:bg-white",
      tag: "inline-flex items-center gap-1.5 rounded-full border border-slate-200 bg-white/70 px-3 py-1 font-[Inter] text-xs text-sky-700",
      badge:
        "inline-flex items-center gap-2 rounded-full border border-emerald-300 bg-emerald-50 px-4 py-2 font-[Inter] text-xs font-medium text-emerald-800",
      iconWrap:
        "flex h-10 w-10 items-center justify-center rounded-xl border border-slate-200 bg-white/80 text-sky-700",
      header: "fixed inset-x-0 top-0 z-50 border-b border-slate-200 bg-white/85 backdrop-blur-xl",
      navLink:
        "rounded-lg px-3 py-2 font-[Inter] text-sm text-slate-600 transition-all duration-500 hover:bg-slate-100 hover:text-slate-900",
      navMobile: "block rounded-lg px-3 py-2 font-[Inter] text-sm text-sky-700 transition-all duration-500 hover:bg-slate-100",
      logo: "group flex items-center gap-2 font-[Space_Grotesk] text-lg font-semibold text-slate-900",
      logoAccent: "text-sky-700",
      logoDot: "text-violet-700",
      sectionLabel: "font-[Inter] text-xs font-semibold uppercase tracking-widest text-violet-700",
      sectionTitle: "font-[Space_Grotesk] text-3xl font-bold text-slate-900 sm:text-4xl",
      sectionTitlePrefix: "text-sky-600",
      sectionDesc: "mt-5 max-w-2xl font-[Inter] text-base leading-relaxed text-slate-600",
      heroBoot: "font-[Inter] text-sm text-sky-700",
      heroOperator: "block text-sm font-medium tracking-wide text-violet-700",
      heroName: "mt-2 block bg-gradient-to-r from-sky-700 via-violet-700 to-emerald-700 bg-clip-text text-transparent",
      heroSubtitle: "mt-6 max-w-lg font-[Inter] text-base leading-relaxed text-slate-700",
      heroStackPill:
        "flex items-center gap-2 rounded-full border border-slate-200 bg-white/80 px-4 py-2 text-slate-800 shadow-sm transition-all duration-500 hover:bg-white",
      statValue: "font-[Space_Grotesk] text-3xl font-bold text-slate-900",
      statLabel: "mt-1 font-[Inter] text-xs text-slate-600",
      statsBorder: "mt-14 grid grid-cols-3 gap-4 border-t border-slate-200 pt-10",
      photoCaption:
        "absolute inset-x-0 bottom-0 bg-gradient-to-t from-white/95 to-transparent px-4 py-3 font-[Inter] text-xs text-sky-800",
      photoMeta: "mt-3 flex items-center justify-between px-1 font-[Inter] text-xs text-slate-600",
      skillRow: "flex items-center gap-3 rounded-lg px-3 py-2 font-[Inter] text-sm text-slate-600 transition-all duration-500 hover:bg-white/60 hover:text-sky-800",
      skillCategoryTitle: "font-[Space_Grotesk] text-base font-semibold text-slate-900",
      skillCategoryCode: "font-[Space_Grotesk] text-sm font-bold text-violet-700",
      projectTitle: "font-[Space_Grotesk] text-lg font-semibold text-slate-900 transition-all duration-500 group-hover:text-sky-800",
      projectDesc: "mt-3 flex-1 font-[Inter] text-sm leading-relaxed text-slate-600",
      expRole: "font-[Space_Grotesk] text-lg font-semibold text-slate-900",
      expCompany: "mt-1 font-[Inter] text-sm text-sky-700",
      contactLink: "group flex items-center gap-4 font-[Inter] text-sm text-sky-800 transition-all duration-500 hover:translate-x-1",
      socialLink:
        "flex h-11 w-11 items-center justify-center rounded-xl border border-slate-200 text-slate-600 transition-all duration-500 hover:border-violet-300 hover:bg-violet-50 hover:text-violet-700",
      footerText: "font-[Inter] text-sm text-slate-600",
      footerLink: "group flex items-center gap-2 font-[Inter] text-sm text-violet-700 transition-all duration-500 hover:text-violet-900",
      marqueeItem: "flex items-center gap-3 text-slate-600 transition-all duration-500 hover:scale-105 hover:text-sky-700",
      sectionAlt: "bg-white/50 px-6 py-28",
      projectThumb: "relative min-h-[160px] rounded-t-2xl bg-gradient-to-br from-sky-100 via-violet-100 to-emerald-100",
      marquee: "relative overflow-hidden border-y border-slate-200 bg-white/70 py-6",
      marqueeFadeL: "pointer-events-none absolute inset-y-0 left-0 z-10 w-24 bg-gradient-to-r from-sky-50 to-transparent",
      marqueeFadeR: "pointer-events-none absolute inset-y-0 right-0 z-10 w-24 bg-gradient-to-l from-emerald-50 to-transparent",
      pickerPage: "min-h-screen bg-gradient-to-br from-sky-50 via-violet-50 to-emerald-50 px-6 py-16",
      pickerCard: "rounded-2xl border border-slate-200 bg-white/80 shadow-sm backdrop-blur-sm",
      pickerCardLabel: "font-[Space_Grotesk] text-sm font-semibold text-slate-900",
      settingsBtn:
        "flex h-9 w-9 items-center justify-center rounded-full border border-slate-200 bg-white/80 text-sky-700 backdrop-blur-sm transition-all duration-500 hover:bg-white hover:text-violet-700",
      settingsOverlay: "fixed inset-0 z-[100] bg-white/70 backdrop-blur-md",
      modeToggle: "inline-flex rounded-full border border-slate-200 bg-white p-0.5 shadow-sm",
      modeToggleActive: "bg-sky-100 text-sky-800",
    },
  },
  minimal_mono: {
    colors: {
      bg: "#ffffff",
      panel: "#fafafa",
      accent: "#000000",
      accent2: "#525252",
      highlight: "#171717",
    },
    classes: {
      root: "min-h-screen bg-white font-[Inter] text-neutral-600 antialiased",
      sectionAlt: "bg-neutral-50 px-6 py-32",
      textPrimary: "text-neutral-900",
      textMuted: "text-neutral-500",
      textAccent: "text-neutral-900",
      panel: "border-t border-neutral-200 pt-8 transition-opacity duration-700 hover:opacity-80",
      btnPrimary: "inline-flex items-center gap-2 bg-neutral-900 px-6 py-3 font-[Inter] text-sm font-medium text-white",
      btnSecondary: "inline-flex items-center gap-2 border border-neutral-300 px-6 py-3 font-[Inter] text-sm font-medium text-neutral-900",
      header: "fixed inset-x-0 top-0 z-50 border-b border-neutral-200 bg-white/90 backdrop-blur-sm",
      footer: "border-t border-neutral-200 px-6 py-12",
      pickerPage: "min-h-screen bg-white px-6 py-20",
      settingsOverlay: "fixed inset-0 z-[100] bg-white/90 backdrop-blur-sm",
      modeToggle: "inline-flex rounded-sm border border-neutral-300 p-0.5",
      modeToggleActive: "bg-neutral-900 text-white",
      showMarquee: false,
    },
  },
  brutalist_dev: {
    colors: {
      bg: "#ffffff",
      panel: "#ffffff",
      accent: "#000000",
      accent2: "#ff0000",
      highlight: "#0000ff",
    },
    classes: {
      root: "min-h-screen bg-white font-[IBM_Plex_Mono] text-black",
      sectionAlt: "border-b-4 border-black bg-neutral-50 px-4 py-16 sm:px-6",
      textPrimary: "text-black",
      textMuted: "text-neutral-700",
      panel: "border-4 border-black bg-white p-6 shadow-[6px_6px_0_0_#000]",
      btnPrimary:
        "inline-flex items-center gap-2 border-4 border-black bg-black px-6 py-3 font-[IBM_Plex_Mono] text-xs font-bold uppercase text-white shadow-[4px_4px_0_0_#000]",
      badge: "inline-flex items-center gap-2 border-4 border-black bg-white px-4 py-2 font-[IBM_Plex_Mono] text-xs font-bold uppercase text-black",
      header: "fixed inset-x-0 top-0 z-50 border-b-4 border-black bg-white",
      heroOperator: "block text-xs font-bold text-red-600",
      heroName: "mt-2 block text-3xl font-bold text-black sm:text-4xl",
      heroSubtitle: "mt-6 max-w-lg font-[IBM_Plex_Mono] text-sm leading-relaxed text-neutral-800",
      heroStackPill:
        "flex items-center gap-2 border-4 border-black bg-neutral-50 px-3 py-1.5 font-bold uppercase text-black",
      statValue: "font-[IBM_Plex_Mono] text-3xl font-bold text-black",
      statLabel: "mt-1 font-[IBM_Plex_Mono] text-xs font-bold uppercase text-neutral-700",
      footer: "border-t-4 border-black bg-white px-6 py-8 text-black",
      marquee: "overflow-hidden border-y-4 border-black bg-neutral-100 py-4 text-black",
      settingsBtn:
        "flex h-9 w-9 items-center justify-center border-4 border-black bg-white font-bold text-black transition-all duration-200 hover:bg-black hover:text-yellow-300",
      pickerTitle: "font-[IBM_Plex_Mono] text-2xl font-bold uppercase text-black sm:text-3xl",
      pickerSubtitle: "font-[IBM_Plex_Mono] text-xs text-neutral-800",
      pickerCardLabel: "font-[IBM_Plex_Mono] text-[10px] font-bold uppercase text-black",
      settingsOverlay: "fixed inset-0 z-[100] bg-white/90",
      modeToggle: "inline-flex border-4 border-black bg-white p-0.5",
      modeToggleActive: "bg-black text-yellow-300",
    },
  },
  neo_editorial: {
    colors: {
      bg: "#f5f2eb",
      panel: "#fffdf8",
      accent: "#2d4a3e",
      accent2: "#8b5a3c",
      highlight: "#1a1a1a",
    },
    classes: {
      root: "min-h-screen bg-[#f5f2eb] font-['Source_Sans_3'] text-stone-700",
      sectionAlt: "bg-[#ebe6dc] px-6 py-24",
      textPrimary: "text-stone-900",
      textMuted: "text-stone-500",
      panel: "rounded-sm border border-stone-200 bg-[#fffdf8] p-8 shadow-sm",
      header: "fixed inset-x-0 top-0 z-50 border-b border-stone-300 bg-[#f5f2eb]/95 backdrop-blur-sm",
      projectThumb: "relative min-h-[160px] rounded-t-sm bg-gradient-to-br from-stone-200 to-stone-300",
      marquee: "overflow-hidden border-y border-stone-300 bg-[#ebe6dc] py-5",
      marqueeFadeL: "pointer-events-none absolute inset-y-0 left-0 z-10 w-20 bg-gradient-to-r from-[#ebe6dc] to-transparent",
      pickerPage: "min-h-screen bg-[#f5f2eb] px-6 py-20",
      settingsOverlay: "fixed inset-0 z-[100] bg-stone-900/20 backdrop-blur-sm",
      modeToggle: "inline-flex rounded-sm border border-stone-300 bg-[#fffdf8] p-0.5",
      modeToggleActive: "bg-[#2d4a3e] text-[#f5f2eb]",
    },
  },
}

export const darkPatches: Record<ThemeName, LightPatch> = {
  minimal_mono: {
    colors: {
      bg: "#0a0a0a",
      panel: "#141414",
      accent: "#ffffff",
      accent2: "#a3a3a3",
      highlight: "#fafafa",
    },
    classes: {
      root: "min-h-screen bg-neutral-950 font-[Inter] text-neutral-300 antialiased",
      sectionAlt: "bg-neutral-900 px-6 py-32",
      textPrimary: "text-neutral-100",
      textMuted: "text-neutral-400",
      textAccent: "text-white",
      textAccent2: "text-neutral-300",
      heroBoot: "font-[Inter] text-sm text-neutral-400",
      heroOperator: "block text-xs font-medium uppercase tracking-[0.25em] text-neutral-400",
      heroName: "mt-3 block font-[Inter] text-4xl font-light tracking-tight text-neutral-100 sm:text-5xl",
      heroSubtitle: "mt-8 max-w-lg font-[Inter] text-lg leading-relaxed text-neutral-400",
      heroStackPill:
        "flex items-center gap-2 rounded-sm border border-neutral-700 bg-neutral-900 px-3 py-1.5 text-neutral-200",
      statValue: "font-[Inter] text-3xl font-light text-neutral-100",
      statLabel: "mt-1 font-[Inter] text-xs text-neutral-500",
      statsBorder: "mt-16 grid grid-cols-3 gap-8 border-t border-neutral-800 pt-10",
      panel: "border-t border-neutral-800 pt-8 transition-opacity duration-700 hover:opacity-80",
      btnPrimary: "inline-flex items-center gap-2 bg-white px-6 py-3 font-[Inter] text-sm font-medium text-neutral-950",
      btnSecondary: "inline-flex items-center gap-2 border border-neutral-600 px-6 py-3 font-[Inter] text-sm font-medium text-white",
      header: "fixed inset-x-0 top-0 z-50 border-b border-neutral-800 bg-neutral-950/90 backdrop-blur-sm",
      footer: "border-t border-neutral-800 px-6 py-12",
      photoInner: "relative aspect-square overflow-hidden border border-neutral-800 bg-neutral-900",
      photoCaption: "mt-4 font-[Inter] text-xs text-neutral-500",
      pickerTitle: "font-[Inter] text-3xl font-light tracking-tight text-neutral-100",
      pickerSubtitle: "font-[Inter] text-sm text-neutral-400",
      pickerCard:
        "group cursor-pointer border border-neutral-700 bg-neutral-900/50 text-left transition-all duration-300 hover:border-neutral-500",
      pickerCardActive: "border-neutral-300 bg-neutral-800",
      pickerCardLabel: "font-[Inter] text-sm font-medium text-neutral-100",
      pickerBtn:
        "inline-flex bg-white px-8 py-3 font-[Inter] text-sm font-medium text-neutral-950 transition-all duration-300 hover:bg-neutral-200 disabled:opacity-40",
      settingsBtn:
        "flex h-9 w-9 items-center justify-center text-neutral-400 transition-colors duration-300 hover:text-neutral-100",
      pickerPage: "min-h-screen bg-neutral-950 px-6 py-20",
      settingsOverlay: "fixed inset-0 z-[100] bg-black/80 backdrop-blur-sm",
      modeToggle: "inline-flex rounded-sm border border-neutral-700 p-0.5",
      modeToggleActive: "bg-white text-neutral-950",
    },
  },
  neo_editorial: {
    colors: {
      bg: "#1c1917",
      panel: "#292524",
      accent: "#a8c5b5",
      accent2: "#d4a574",
      highlight: "#fafaf9",
    },
    classes: {
      root: "min-h-screen bg-stone-900 font-['Source_Sans_3'] text-stone-300",
      sectionAlt: "bg-stone-950 px-6 py-24",
      textPrimary: "text-stone-100",
      textMuted: "text-stone-400",
      textAccent: "text-[#a8c5b5]",
      textAccent2: "text-[#d4a574]",
      heroBoot: "font-['Source_Sans_3'] text-sm italic text-[#d4a574]",
      heroOperator: "block font-['Source_Sans_3'] text-xs font-semibold uppercase tracking-widest text-[#d4a574]",
      heroName: "mt-2 block font-['Playfair_Display'] text-4xl font-semibold leading-tight text-stone-100 sm:text-5xl",
      heroSubtitle:
        "mt-6 max-w-lg font-['Source_Sans_3'] text-lg leading-relaxed text-stone-400",
      heroStackPill:
        "flex items-center gap-2 rounded-sm border border-stone-600 bg-stone-800 px-3 py-2 font-['Source_Sans_3'] text-sm text-stone-200",
      statValue: "font-['Playfair_Display'] text-4xl font-semibold text-stone-100",
      statLabel: "mt-1 font-['Source_Sans_3'] text-xs text-stone-500",
      statsBorder: "mt-14 grid grid-cols-3 gap-6 border-t border-stone-700 pt-10",
      panel: "rounded-sm border border-stone-700 bg-stone-800 p-8 shadow-sm",
      btnSecondary:
        "inline-flex items-center gap-2 rounded-sm border border-stone-500 px-7 py-3 font-['Source_Sans_3'] text-sm font-semibold text-stone-200 transition-all duration-500 hover:border-[#a8c5b5] hover:text-[#a8c5b5]",
      header: "fixed inset-x-0 top-0 z-50 border-b border-stone-700 bg-stone-900/95 backdrop-blur-sm",
      sectionTitle: "font-['Playfair_Display'] text-3xl font-semibold text-stone-100 sm:text-4xl",
      photoInner:
        "relative aspect-[4/5] overflow-hidden rounded-sm border border-stone-600 bg-stone-800",
      photoCaption: "mt-4 font-['Source_Sans_3'] text-xs italic text-stone-400",
      photoMeta: "mt-2 font-['Source_Sans_3'] text-xs text-stone-500",
      projectThumb: "relative min-h-[160px] rounded-t-sm bg-stone-800",
      marquee: "overflow-hidden border-y border-stone-700 bg-stone-950 py-5",
      marqueeFadeL: "pointer-events-none absolute inset-y-0 left-0 z-10 w-20 bg-gradient-to-r from-stone-950 to-transparent",
      marqueeFadeR: "pointer-events-none absolute inset-y-0 right-0 z-10 w-20 bg-gradient-to-l from-stone-950 to-transparent",
      pickerTitle: "font-['Playfair_Display'] text-3xl font-semibold text-stone-100 sm:text-4xl",
      pickerSubtitle: "font-['Source_Sans_3'] text-sm text-stone-400",
      pickerCard:
        "group cursor-pointer rounded-sm border border-stone-600 bg-stone-800/80 p-2 text-left shadow-sm transition-all duration-500 hover:border-stone-500",
      pickerCardActive: "border-[#a8c5b5] ring-1 ring-[#a8c5b5]/40",
      pickerCardLabel: "font-['Playfair_Display'] text-sm font-semibold text-stone-100",
      pickerBtn:
        "inline-flex rounded-sm border border-stone-600 bg-[#a8c5b5] px-8 py-3 font-['Source_Sans_3'] text-sm font-semibold text-stone-900 transition-all duration-500 hover:bg-[#b8d5c5] disabled:opacity-40",
      settingsBtn:
        "flex h-9 w-9 items-center justify-center rounded-sm border border-stone-600 text-stone-300 transition-all duration-500 hover:bg-stone-800 hover:text-stone-100",
      pickerPage: "min-h-screen bg-stone-900 px-6 py-20",
      settingsOverlay: "fixed inset-0 z-[100] bg-black/70 backdrop-blur-sm",
      modeToggle: "inline-flex rounded-sm border border-stone-600 bg-stone-800 p-0.5",
      modeToggleActive: "bg-[#a8c5b5] text-stone-900",
    },
  },
  cyberpunk: { colors: {}, classes: {} },
  glassmorphism: { colors: {}, classes: {} },
  brutalist_dev: { colors: {}, classes: {} },
}
