import { createTheme } from "../themeFactory"
import { lightPatches } from "../lightPatches"

const darkBundle = {
  colors: {
    bg: "#ffff00",
    panel: "#ffffff",
    accent: "#000000",
    accent2: "#ff0000",
    highlight: "#0000ff",
  },
  classes: {
    root: "min-h-screen bg-yellow-300 font-[IBM_Plex_Mono] text-black",
    main: "relative z-10",
    section: "border-b-4 border-black px-4 py-16 sm:px-6",
    sectionAlt: "border-b-4 border-black bg-white px-4 py-16 sm:px-6",
    container: "mx-auto max-w-6xl",
    fontSans: "font-[IBM_Plex_Mono]",
    fontDisplay: "font-[IBM_Plex_Mono]",
    textTransform: "uppercase",
    textPrimary: "text-black",
    textMuted: "text-black/70",
    textAccent: "text-black",
    textAccent2: "text-red-600",
    textHighlight: "text-blue-700",
    panel:
      "border-4 border-black bg-white p-6 shadow-[6px_6px_0_0_#000] transition-all duration-200 hover:translate-x-1 hover:translate-y-1 hover:shadow-[3px_3px_0_0_#000]",
    btnPrimary:
      "inline-flex items-center gap-2 border-4 border-black bg-black px-6 py-3 font-[IBM_Plex_Mono] text-xs font-bold uppercase text-yellow-300 shadow-[4px_4px_0_0_#000] transition-all duration-200 hover:translate-x-0.5 hover:translate-y-0.5 hover:shadow-[2px_2px_0_0_#000]",
    btnSecondary:
      "inline-flex items-center gap-2 border-4 border-black bg-white px-6 py-3 font-[IBM_Plex_Mono] text-xs font-bold uppercase text-black shadow-[4px_4px_0_0_#000] transition-all duration-200 hover:bg-yellow-200",
    tag: "inline-flex items-center gap-1.5 border-2 border-black bg-yellow-200 px-2 py-0.5 font-[IBM_Plex_Mono] text-xs font-bold uppercase",
    input:
      "w-full border-4 border-black bg-white px-4 py-3 font-[IBM_Plex_Mono] text-sm text-black placeholder:text-black/40 outline-none focus:bg-yellow-100",
    badge:
      "inline-flex items-center gap-2 border-4 border-black bg-red-500 px-4 py-2 font-[IBM_Plex_Mono] text-xs font-bold uppercase text-white",
    iconWrap:
      "flex h-10 w-10 items-center justify-center border-4 border-black bg-white",
    iconHover: "transition-transform duration-200 hover:rotate-3",
    header: "fixed inset-x-0 top-0 z-50 border-b-4 border-black bg-yellow-300",
    navLink:
      "border-2 border-transparent px-3 py-2 font-[IBM_Plex_Mono] text-xs font-bold uppercase transition-all duration-200 hover:border-black hover:bg-white",
    navMobile: "block border-2 border-black bg-white px-3 py-2 font-[IBM_Plex_Mono] text-xs font-bold uppercase",
    logo: "group flex items-center gap-2 font-[IBM_Plex_Mono] text-sm font-bold uppercase",
    logoAccent: "bg-black px-1 text-yellow-300",
    logoDot: "text-red-600",
    sectionLabel: "font-[IBM_Plex_Mono] text-xs font-bold uppercase tracking-widest text-red-600",
    sectionTitle: "font-[IBM_Plex_Mono] text-2xl font-bold uppercase sm:text-3xl",
    sectionTitlePrefix: "text-blue-700",
    sectionDivider: "mt-3 h-1 w-full bg-black",
    sectionDesc: "mt-4 max-w-2xl font-[IBM_Plex_Mono] text-sm leading-relaxed",
    hero: "relative flex min-h-screen items-center border-b-4 border-black px-4 pt-24 sm:px-6",
    heroBadge: "",
    heroBoot: "font-[IBM_Plex_Mono] text-sm font-bold",
    heroOperator: "block text-xs font-bold text-red-600",
    heroName: "mt-2 block text-3xl font-bold sm:text-4xl",
    heroSubtitle: "mt-6 max-w-lg font-[IBM_Plex_Mono] text-sm leading-relaxed",
    heroStackPill:
      "flex items-center gap-2 border-4 border-black bg-white px-3 py-2 font-[IBM_Plex_Mono] text-xs font-bold uppercase",
    statPanel: "",
    statValue: "font-[IBM_Plex_Mono] text-3xl font-bold",
    statLabel: "mt-1 font-[IBM_Plex_Mono] text-xs font-bold uppercase",
    statsBorder: "mt-12 grid grid-cols-3 gap-4 border-t-4 border-black pt-8",
    photoGlow: "hidden",
    photoPanel: "border-4 border-black bg-white p-2 shadow-[8px_8px_0_0_#000]",
    photoInner: "relative aspect-square overflow-hidden border-4 border-black bg-black",
    photoCaption:
      "mt-2 border-2 border-black bg-black px-2 py-1 font-[IBM_Plex_Mono] text-[10px] font-bold uppercase text-yellow-300",
    photoMeta: "mt-2 font-[IBM_Plex_Mono] text-[10px] font-bold uppercase",
    skillRow:
      "flex items-center gap-3 border-2 border-black bg-yellow-100 px-3 py-2 font-[IBM_Plex_Mono] text-sm font-bold uppercase",
    skillCategoryTitle: "font-[IBM_Plex_Mono] text-sm font-bold uppercase",
    skillCategoryCode: "font-[IBM_Plex_Mono] text-lg font-bold text-blue-700",
    skillDivider: "mb-4 flex items-center gap-3 border-b-4 border-black pb-4",
    projectThumb: "relative min-h-[140px] border-b-4 border-black bg-black",
    projectFeatured:
      "absolute left-0 top-0 border-4 border-black bg-red-500 px-3 py-1 font-[IBM_Plex_Mono] text-[10px] font-bold uppercase text-white",
    projectMeta: "absolute bottom-2 right-3 font-[IBM_Plex_Mono] text-[10px] font-bold text-yellow-300",
    projectTitle: "font-[IBM_Plex_Mono] text-sm font-bold uppercase",
    projectDesc: "mt-3 flex-1 font-[IBM_Plex_Mono] text-xs leading-relaxed normal-case",
    projectLinkPrimary:
      "font-[IBM_Plex_Mono] text-xs font-bold uppercase underline decoration-4",
    projectLinkSecondary:
      "font-[IBM_Plex_Mono] text-xs font-bold uppercase text-blue-700 underline decoration-4",
    projectLinksBorder: "mt-5 flex gap-6 border-t-4 border-black pt-4",
    expPanel: "grid gap-4 border-4 border-black bg-white p-6 md:grid-cols-[120px_1fr]",
    expNumber: "font-[IBM_Plex_Mono] text-4xl font-bold text-blue-700",
    expPeriod: "mt-2 block font-[IBM_Plex_Mono] text-[10px] font-bold uppercase",
    expRole: "font-[IBM_Plex_Mono] text-sm font-bold uppercase",
    expCompany: "mt-1 font-[IBM_Plex_Mono] text-xs font-bold text-red-600",
    expBullet: "shrink-0 font-bold text-red-600",
    expItem: "flex gap-2 font-[IBM_Plex_Mono] text-xs leading-relaxed normal-case",
    expSidebar: "border-b-4 border-black pb-4 md:border-b-0 md:border-r-4 md:pb-0 md:pr-6",
    contactLabel: "mb-2 block font-[IBM_Plex_Mono] text-xs font-bold uppercase",
    contactIconBox: "flex h-10 w-10 items-center justify-center border-4 border-black bg-yellow-200",
    contactLink: "flex items-center gap-4 font-[IBM_Plex_Mono] text-xs font-bold uppercase underline",
    socialLink:
      "flex h-10 w-10 items-center justify-center border-4 border-black bg-white transition-all duration-200 hover:bg-black hover:text-yellow-300",
    footer: "border-t-4 border-black bg-black px-6 py-8 text-yellow-300",
    footerText: "font-[IBM_Plex_Mono] text-[10px] font-bold uppercase",
    footerLink: "font-[IBM_Plex_Mono] text-[10px] font-bold uppercase text-yellow-300 underline",
    marquee: "overflow-hidden border-y-4 border-black bg-black py-4 text-yellow-300",
    marqueeFadeL: "hidden",
    marqueeFadeR: "hidden",
    marqueeItem: "flex items-center gap-3 font-[IBM_Plex_Mono] text-xs font-bold uppercase",
    traitCode: "font-[IBM_Plex_Mono] text-xs font-bold text-blue-700",
    terminalPanel: "hidden",
    terminalInner: "hidden",
    pickerPage: "min-h-screen border-b-4 border-black bg-yellow-300 px-6 py-16",
    pickerTitle: "font-[IBM_Plex_Mono] text-3xl font-bold uppercase sm:text-4xl",
    pickerSubtitle: "mt-3 font-[IBM_Plex_Mono] text-sm",
    pickerGrid: "mt-12 grid gap-6 sm:grid-cols-2",
    pickerCard:
      "group cursor-pointer border-4 border-black bg-white p-4 text-left shadow-[8px_8px_0_0_#000] transition-all duration-200 hover:translate-x-1 hover:translate-y-1 hover:shadow-[4px_4px_0_0_#000]",
    pickerCardActive: "bg-yellow-200",
    pickerPreview: "h-24 border-4 border-black bg-yellow-300 p-3",
    pickerCardLabel: "mt-4 font-[IBM_Plex_Mono] text-sm font-bold uppercase",
    pickerCardDesc: "mt-2 font-[IBM_Plex_Mono] text-xs normal-case",
    pickerBtn:
      "mt-8 inline-flex border-4 border-black bg-black px-8 py-3 font-[IBM_Plex_Mono] text-xs font-bold uppercase text-yellow-300 shadow-[6px_6px_0_0_#000] disabled:opacity-40",
    settingsBtn:
      "flex h-9 w-9 items-center justify-center border-4 border-black bg-white font-bold transition-all duration-200 hover:bg-black hover:text-yellow-300",
    modeToggle: "inline-flex border-4 border-black bg-yellow-300 p-0.5",
    modeToggleActive: "bg-black text-yellow-300",
    settingsOverlay: "fixed inset-0 z-[100] bg-black/80",
    settingsPanel: "mx-auto mt-16 max-w-4xl px-6",
    revealDuration: "400ms",
    showTerminal: false,
    showMarquee: true,
    showPhotoScan: false,
    showScanlines: false,
    showGlitch: false,
    showGridFloor: false,
    showHeroGlow: false,
  },
}

export const brutalistDevTheme = createTheme(
  {
    name: "brutalist_dev",
    label: "Brutalist Dev",
    description: "Raw engineering UI with hard edges, visible structure, and system fonts.",
    font: "IBM Plex Mono + system-ui",
    layout: "boxy grid, visible borders",
    effects: "none",
    tailwindClasses: "bg-yellow-300 border-4 border-black font-mono uppercase",
    defaultMode: "dark",
  },
  darkBundle,
  lightPatches.brutalist_dev,
)
