import { createThemeWithLightDefault } from "../themeFactory"
import { darkPatches } from "../lightPatches"

const lightBundle = {
  colors: {
    bg: "#ffffff",
    panel: "#fafafa",
    accent: "#000000",
    accent2: "#525252",
    highlight: "#171717",
  },
  classes: {
    root: "min-h-screen bg-white font-[Inter] text-neutral-600 antialiased",
    main: "relative z-10",
    section: "px-6 py-32",
    sectionAlt: "bg-neutral-50 px-6 py-32",
    container: "mx-auto max-w-3xl",
    fontSans: "font-[Inter]",
    fontDisplay: "font-[Inter]",
    textTransform: "normal-case",
    textPrimary: "text-neutral-900",
    textMuted: "text-neutral-500",
    textAccent: "text-neutral-900",
    textAccent2: "text-neutral-600",
    textHighlight: "text-neutral-900",
    panel: "border-t border-neutral-200 pt-8 transition-opacity duration-700 hover:opacity-80",
    btnPrimary:
      "inline-flex items-center gap-2 bg-neutral-900 px-6 py-3 font-[Inter] text-sm font-medium text-white transition-all duration-300 hover:bg-neutral-700",
    btnSecondary:
      "inline-flex items-center gap-2 border border-neutral-300 px-6 py-3 font-[Inter] text-sm font-medium text-neutral-900 transition-all duration-300 hover:border-neutral-900",
    tag: "inline-flex items-center gap-1.5 font-[Inter] text-xs text-neutral-500 transition-colors duration-300 hover:text-neutral-900",
    input:
      "w-full border-0 border-b border-neutral-300 bg-transparent px-0 py-3 font-[Inter] text-sm text-neutral-900 placeholder:text-neutral-400 outline-none transition-all duration-300 focus:border-neutral-900",
    badge:
      "inline-flex items-center gap-2 font-[Inter] text-xs font-medium tracking-wide text-neutral-500",
    iconWrap: "flex h-9 w-9 items-center justify-center text-neutral-900",
    iconHover: "transition-opacity duration-300 hover:opacity-60",
    header:
      "fixed inset-x-0 top-0 z-50 border-b border-neutral-200 bg-white/90 backdrop-blur-sm",
    navLink:
      "px-2 py-2 font-[Inter] text-sm text-neutral-500 transition-colors duration-300 hover:text-neutral-900",
    navMobile: "block py-2 font-[Inter] text-sm text-neutral-900",
    logo: "group flex items-center gap-3 font-[Inter] text-sm font-semibold tracking-tight text-neutral-900",
    logoAccent: "text-neutral-900",
    logoDot: "text-neutral-400",
    sectionLabel: "font-[Inter] text-xs font-medium uppercase tracking-[0.2em] text-neutral-400",
    sectionTitle: "font-[Inter] text-3xl font-light tracking-tight text-neutral-900 sm:text-4xl",
    sectionTitlePrefix: "hidden",
    sectionDivider: "mt-6 h-px w-full bg-neutral-200",
    sectionDesc: "mt-6 max-w-xl font-[Inter] text-base leading-relaxed text-neutral-500",
    hero: "relative flex min-h-screen items-center px-6 pt-28",
    heroBadge: "",
    heroBoot: "font-[Inter] text-sm text-neutral-400",
    heroOperator: "block text-xs font-medium uppercase tracking-[0.25em] text-neutral-400",
    heroName: "mt-3 block font-[Inter] text-4xl font-light tracking-tight text-neutral-900 sm:text-5xl",
    heroSubtitle: "mt-8 max-w-lg font-[Inter] text-lg leading-relaxed text-neutral-500",
    heroStackPill:
      "flex items-center gap-2 font-[Inter] text-sm text-neutral-600 transition-colors duration-300 hover:text-neutral-900",
    statPanel: "border-t border-neutral-200 pt-6",
    statValue: "font-[Inter] text-3xl font-light text-neutral-900",
    statLabel: "mt-1 font-[Inter] text-xs text-neutral-400",
    statsBorder: "mt-20 grid grid-cols-3 gap-8 border-t border-neutral-200 pt-12",
    photoGlow: "hidden",
    photoPanel: "relative transition-opacity duration-500 hover:opacity-90",
    photoInner: "relative aspect-square overflow-hidden bg-neutral-100",
    photoCaption: "mt-4 font-[Inter] text-xs text-neutral-400",
    photoMeta: "hidden",
    skillRow:
      "flex items-center gap-3 border-b border-neutral-100 py-3 font-[Inter] text-sm text-neutral-600 transition-colors duration-300 hover:text-neutral-900",
    skillCategoryTitle: "font-[Inter] text-sm font-medium text-neutral-900",
    skillCategoryCode: "font-[Inter] text-xs text-neutral-400",
    skillDivider: "mb-6 border-b border-neutral-200 pb-4",
    projectThumb: "hidden",
    projectFeatured: "font-[Inter] text-xs text-neutral-400",
    projectMeta: "hidden",
    projectTitle:
      "font-[Inter] text-lg font-medium text-neutral-900 transition-colors duration-300 hover:text-neutral-600",
    projectDesc: "mt-2 flex-1 font-[Inter] text-sm leading-relaxed text-neutral-500",
    projectLinkPrimary:
      "font-[Inter] text-sm text-neutral-900 underline underline-offset-4 transition-opacity duration-300 hover:opacity-60",
    projectLinkSecondary:
      "font-[Inter] text-sm text-neutral-500 underline underline-offset-4 transition-opacity duration-300 hover:opacity-60",
    projectLinksBorder: "mt-6 flex gap-6",
    expPanel: "border-t border-neutral-200 py-10",
    expNumber: "hidden",
    expPeriod: "font-[Inter] text-xs text-neutral-400",
    expRole: "mt-2 font-[Inter] text-lg font-medium text-neutral-900",
    expCompany: "mt-1 font-[Inter] text-sm text-neutral-500",
    expBullet: "hidden",
    expItem: "mt-3 font-[Inter] text-sm leading-relaxed text-neutral-500",
    expSidebar: "mb-4",
    contactLabel: "mb-2 block font-[Inter] text-xs font-medium uppercase tracking-wider text-neutral-400",
    contactIconBox: "hidden",
    contactLink:
      "font-[Inter] text-sm text-neutral-900 underline underline-offset-4 transition-opacity duration-300 hover:opacity-60",
    socialLink:
      "font-[Inter] text-sm text-neutral-500 transition-opacity duration-300 hover:opacity-60",
    footer: "border-t border-neutral-200 px-6 py-12",
    footerText: "font-[Inter] text-xs text-neutral-400",
    footerLink: "font-[Inter] text-xs text-neutral-900 transition-opacity duration-300 hover:opacity-60",
    marquee: "hidden",
    marqueeFadeL: "hidden",
    marqueeFadeR: "hidden",
    marqueeItem: "hidden",
    traitCode: "font-[Inter] text-xs text-neutral-400",
    terminalPanel: "hidden",
    terminalInner: "hidden",
    pickerPage: "min-h-screen bg-white px-6 py-20",
    pickerTitle: "font-[Inter] text-4xl font-light tracking-tight text-neutral-900",
    pickerSubtitle: "mt-4 font-[Inter] text-base text-neutral-500",
    pickerGrid: "mt-16 grid gap-8 sm:grid-cols-2",
    pickerCard:
      "group cursor-pointer border border-neutral-200 p-8 text-left transition-all duration-300 hover:border-neutral-900",
    pickerCardActive: "border-neutral-900 bg-neutral-50",
    pickerPreview: "h-20 bg-neutral-100",
    pickerCardLabel: "mt-6 font-[Inter] text-lg font-medium text-neutral-900",
    pickerCardDesc: "mt-2 font-[Inter] text-sm text-neutral-500",
    pickerBtn:
      "mt-10 inline-flex bg-neutral-900 px-8 py-3 font-[Inter] text-sm font-medium text-white transition-all duration-300 hover:bg-neutral-700 disabled:opacity-40",
    settingsBtn:
      "flex h-9 w-9 items-center justify-center text-neutral-500 transition-colors duration-300 hover:text-neutral-900",
    modeToggle: "inline-flex rounded-sm border border-neutral-300 p-0.5",
    modeToggleActive: "bg-neutral-900 text-white",
    settingsOverlay: "fixed inset-0 z-[100] bg-white/90 backdrop-blur-sm",
    settingsPanel: "mx-auto mt-20 max-w-3xl px-6",
    revealDuration: "600ms",
    showTerminal: false,
    showMarquee: false,
    showPhotoScan: false,
    showScanlines: false,
    showGlitch: false,
    showGridFloor: false,
    showHeroGlow: false,
  },
}

export const minimalMonoTheme = createThemeWithLightDefault(
  {
    name: "minimal_mono",
    label: "Minimal Mono",
    description: "Strict monochrome editorial layout with whitespace and typographic hierarchy.",
    font: "Inter (system)",
    layout: "single-column grid, heavy whitespace",
    effects: "none / subtle fade",
    tailwindClasses: "bg-white text-neutral-900 font-sans tracking-tight",
  },
  lightBundle,
  darkPatches.minimal_mono,
)
